controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

tournament_generate_first_round:
    path: api/tournaments/{id}/generate-first-round
    methods: ['POST']
    defaults:
        _controller: App\Action\Tournament\generateFirstRoundAction
        _api_resource_class: App\Entity\Tournament

tournament_generate_next_round:
    path: api/tournaments/{id}/generate-next-round
    methods: ['POST']
    defaults:
        _controller: App\Action\Tournament\generateNextRoundAction
        _api_resource_class: App\Entity\Tournament